travis:
  secure:
    BINSTAR_TOKEN: Ojn5iMkxZnEWwFPDj2ekj+a/e+PSLoOLcXvNEz7y85F2QKwKj54qlBtIuvW7HzunxwS7enjeY9mUzS6B6AtfqPreqb6BipyKjaJCTqgP+TMDfGLRqU6ZXqtP0/AQxD9pmTvFm3HSXOUHdfbEErkBdYxRvIVUl0P5gOqT6bFtWoG1ak7gl28YxIelVKviClWq/jBP6cmXxXxWR6OvBULbfgNeep9QsU84iaprrSIozBd+Zzd5wka5XKLoK6PWurPytxzi6s6VbOPusyjfokEGCmFNAVOZNnaHvFiR08dAkkn+WgrdzvXr8XqpbqZNmCXXZGN01zl9kd5lCPHk92x7qrbdK3oRIn0NcrRTzBjKZyOUaVBhyOJiHLWQae0siKHlsRMdZwSQLAkjjLQQD0LU3V2gat2ac1y145mOBHX6YGfAWgLOjN0D4Yaw4QVQpBPzW6Lg91ofUmwmMd07/ieFNFOMC98DmKjmoaN4vCIW43Pa52gZrPq3nmiGhunpMhpBhCk3t0YPncfkTY8EHpjzx08ld3+Qk79PQkRS4VRf5XHUr71qmmCcHdvcgmD3EfiO5R5JB9PTQGhEADPk3nU+WGW8GkG0dDq2XeQJqKy8v8mpNXxGtt0Dla/SvhE/UzRcCf9BwvsUvjJ1l0RZLjlo3kqVt/TyrGVbJlng1rIxMsQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
